// next/app/src/lib/component/Data/MagicPaths.svelte
<script lang="ts">
  import ImgIcon from '$lib/component/ImgIcon.svelte';
  import CustomMagicTable from '$lib/component/CustomMagic.svelte';
  export let item: any;
  export let value: any;
  let pinCM: boolean = false;
  let hoverCM: boolean = false;
  $: showCM = pinCM || hoverCM;
  function toggleHover (h: boolean) { hoverCM = h; }
  function togglePin (p: boolean) { pinCM = p; }
</script>

<span class="td-magic-paths">
  <span></span>
  {#if value.F}<ImgIcon name="magicF"/><span class="text">{value.F}</span>{/if}
  {#if value.A}<ImgIcon name="magicA"/><span class="text">{value.A}</span>{/if}
  {#if value.W}<ImgIcon name="magicW"/><span class="text">{value.W}</span>{/if}
  {#if value.E}<ImgIcon name="magicE"/><span class="text">{value.E}</span>{/if}
  {#if value.S}<ImgIcon name="magicS"/><span class="text">{value.S}</span>{/if}
  {#if value.N}<ImgIcon name="magicN"/><span class="text">{value.N}</span>{/if}
  {#if value.D}<ImgIcon name="magicD"/><span class="text">{value.D}</span>{/if}
  {#if value.G}<ImgIcon name="magicG"/><span class="text">{value.G}</span>{/if}
  {#if value.B}<ImgIcon name="magicB"/><span class="text">{value.B}</span>{/if}
  {#if value.H}<ImgIcon name="magicH"/><span class="text">{value.H}</span>{/if}
  {#if item.custommagic}
    <span
      tabindex="0"
      role="button"
      class={`custom-magic-lvl${hoverCM ? ' cm-hover' : ''}${pinCM ? ' cm-pinned' : ''}`}
      on:pointerenter={function () { toggleHover(true); } }
      on:pointerleave={function () { toggleHover(false); } }
      on:click={function () { togglePin(!pinCM); } }
      on:keydown={function ({ key }) { if (key === ' ') { togglePin(!pinCM); } } }
    >
      <ImgIcon name="custommagic"/>
      <span class="text">{value.U}</span>
    </span>
  {/if}
  {#if value.R}<ImgIcon name="research"/><span class="text">{value.R}</span>{/if}
</span>
{#if showCM }
  <aside>
    <CustomMagicTable customMagic={item.custommagic}/>
  </aside>
{/if}


<style lang="less">
  .td-magic-paths {
    align-self: stretch;
    display: flex;
    align-items: center;
    position: relative;
    user-select: none;
    & > span {
      position: relative;
      top: 1px;
      margin-inline-end: 2px;
    }

    & :global(.img-icon) {
      margin: 2px;
      height: 16px;
      width: 16px;
    }
    & :global(.img-icon[data-name="magicH"]) { margin-right: 5px; }
    & :global(.img-icon[data-name="magicB"]) { position: relative; top: 2px; }

    & > .custom-magic-lvl {
      & > span {
        margin-inline-end: 2px;
      }
      & > :global(.img-icon[data-name="custommagic"]) {
        position: relative;
        top: 1px;
        margin-right: -1px;
      }
      top: 0;
      border-left: solid 2px transparent;
      border-right: solid 2px transparent;
      align-self: stretch;
      display: flex;
      align-items: center;
      cursor: pointer;
      &.cm-hover { background-color: #333; }
      &.cm-pinned { background-color: var(--se-color); }
      color: var(--ln-color);
      & > :global(.img-icon) {
        height: 16px;
        width: 16px;
      }
    }


  }
  aside {
    pointer-events: none;
    z-index: 1000;
    color: var(--fg-color) !important; // hehe
    position: absolute;
    top: 100%;
    left: -2px;
    opacity: 1;
  }



</style>

// next/app/src/MagicPaths.vue
<script setup lang="ts">
  import { ref, computed } from 'vue';
  import { icons } from './icon';
  import { queryMouse } from './mouse';
  import ImgIcon from './ImgIcon.vue';
  defineProps<{ value: any; item?: any }>();
  defineOptions({ inheritAttrs: false })
  const pInCM = ref(false);
  //const pPin = ref<null|string>(null);
  const pPin = ref(false);

  function togglePinned (pin?: boolean) {
    pin ??= !pPin.value;
    if (pin) {
      //const { x, y } = queryMouse();
      //pPin.value = `--m-x: ${x}px; --m-y: ${y}px`;
      pPin.value = true;
    } else {
      pPin.value = false;
    }
  }

</script>

<template>
  <span v-if="value" class="td-magic-paths">
    <template v-if="value.F"><ImgIcon name="magicF"/>{{ value.F }}</template>
    <template v-if="value.A"><ImgIcon name="magicA"/>{{ value.A }}</template>
    <template v-if="value.W"><ImgIcon name="magicW"/>{{ value.W }}</template>
    <template v-if="value.E"><ImgIcon name="magicE"/>{{ value.E }}</template>
    <template v-if="value.S"><ImgIcon name="magicS"/>{{ value.S }}</template>
    <template v-if="value.N"><ImgIcon name="magicN"/>{{ value.N }}</template>
    <template v-if="value.D"><ImgIcon name="magicD"/>{{ value.D }}</template>
    <template v-if="value.G"><ImgIcon name="magicG"/>{{ value.G }}</template>
    <template v-if="value.B"><ImgIcon name="magicB"/>{{ value.B }}</template>
    <template v-if="value.H"><ImgIcon name="magicH" style="margin-right: 4px"/>{{ value.H }}</template>
    <span
      v-if="item?.custommagic"
      class="custom-magic-lvl"
      :class="{ 'custom-magic-lvl--pinned': pPin }"
      @pointerenter.passive="pInCM = true;"
      @pointerleave.passive="pInCM = false;"
      @click="togglePinned()"
      :style="{ color: `var(--${pPin ? 'hl' : 'ln' }-color)`}"
    >
      <ImgIcon  name="custommagic"/>
      {{ value.U }}
        <div
          class="here-panel custom-magic"
          :class="{
            'here-panel--pinned': pPin,
            'here-panel--hover': !pPin && pInCM,
          }"
        >
          <table>
            <thead><th>Paths</th><th>Level</th><th>Chance</th></thead>
            <tbody>
              <tr v-for="{ chance, lvl, paths } of item.custommagic.spec">
                <td class="pathicons">
                  <ImgIcon v-for="p in paths" :name="`magic${p}`" />
                </td>
                <td>+{{ lvl }}</td>
                <td>{{ chance }}%</td>
              </tr>
            </tbody>
          </table>
        </div>
      <!--<Teleport to="body" :disabled="pPin"> </Teleport>-->
    </span>
    <template v-if="item?.research != null">
      <ImgIcon name="research" style="margin-left: 4px"/>{{ item.research }}
    </template>
  </span>
</template>

<style lang="less">
  .td-magic-paths {
    display: flex;
    align-items: center;
    user-select: none;
  }
  .td-magic-paths > img {
    margin-right: 2px;
    &:not(:first-child) {
      margin-left: 0.25em;
    }
    height: 16px;
    width: 16px;
  }

  .td-magic-paths > .custom-magic-lvl {
    color: var(--ln-color);
    /*&:hover { filter: brightness(1.25); }*/
    align-self: stretch;
    display: flex;
    align-items: center;
    cursor: help;
    & > img {
      transform: translate(0, -1px);
      margin-right: 0;
      margin-left: 0.1em;
      height: 16px;
      width: 16px;
    }
    &.custom-magic-lvl {
      &::before {
        position: absolute;
        height: 16px;
        width: 16px;
        background-color: var(--se-color);

      }
    }
  }

  .custom-magic {
    table {
      background: #222;
      border: 1px solid var(--se-color);
    }
    & .pathicons {
      padding: 4px 4px;
      height: 22px;
      display: flex;
      align-items: center;
      > img { height: 16px; width: 16px; margin-right: 2px; }
    }
  }

  // TODO - move out
  .here-panel {
    pointer-events: none;
    z-index: 1000;
    color: var(--fg-color) !important; // hehe
    position: absolute;
    top: 100%;
    left: -2px;
    opacity: 0;
    &.here-panel--hover {
      pointer-events: unset;
      opacity: 1;
    }
    &.here-panel--pinned {
      pointer-events: unset;
      opacity: 1;
    }

    /*
    &.here-panel--hover {
      //position: fixed;
      //top: 0;
      //left: 0;
      //transform: translate(var(--m-x), var(--m-y));

      //transform: translate(0, 4px);
      pointer-events: unset;

    }

    &.here-panel--pinned {
      position: absolute;
      top: 100%;
      left: 0;
      //transform: translate(0, 4px);
      pointer-events: unset;
    }
    */
  }
</style>
